"""Add SkillOpt models

Revision ID: c57f9d033a44
Revises: 20260717trajectory
Create Date: 2026-07-17 20:25:51.294947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c57f9d033a44'
down_revision: Union[str, None] = '20260717trajectory'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'bushido_settings',
               existing_type=sqlite.JSON(),
               type_=shogun.db.base.JSONType(),
               nullable=False,
               existing_server_default=sa.text('\'{"nightly_consolidation": true, "weekly_performance_audit": true, "skill_health_check": true, "persona_drift_check": false}\''))
    op.add_column('nexus_external_agents', sa.Column('endpoint_url', sa.String(length=1000), nullable=True))
    op.add_column('nexus_external_agents', sa.Column('direction', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nexus_external_agents', 'direction')
    op.drop_column('nexus_external_agents', 'endpoint_url')
    op.alter_column('agents', 'bushido_settings',
               existing_type=shogun.db.base.JSONType(),
               type_=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text('\'{"nightly_consolidation": true, "weekly_performance_audit": true, "skill_health_check": true, "persona_drift_check": false}\''))
    # ### end Alembic commands ###
